# Generated by Django 5.0.7 on 2024-07-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='forMore',
            field=models.TextField(default='For more info, check the github!'),
        ),
    ]
