# Generated by Django 5.0.7 on 2024-07-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_formore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='forMore',
            field=models.URLField(blank=True),
        ),
    ]
