# Generated by Django 5.0.7 on 2024-07-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_formore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='forMore',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
