# Generated by Django 5.0.7 on 2024-07-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_formore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='forMore',
            new_name='urlInsert',
        ),
        migrations.AddField(
            model_name='project',
            name='whatUrlSays',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
