# Generated by Django 5.0.7 on 2024-07-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_formore_project_urlinsert_project_whaturlsays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
