# Generated by Django 5.0.7 on 2024-07-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dif1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pid', models.IntegerField(blank=True)),
                ('Name', models.CharField(max_length=200)),
                ('Audio', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dif2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pid', models.IntegerField(blank=True)),
                ('Name', models.CharField(max_length=200)),
                ('Audio', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Global',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dif1', models.IntegerField(blank=True)),
                ('same', models.IntegerField(blank=True)),
                ('dif2', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Same',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pid', models.IntegerField(blank=True)),
                ('Name', models.CharField(max_length=200)),
                ('Audio', models.URLField(blank=True)),
            ],
        ),
    ]
