# Generated by Django 5.0.7 on 2024-07-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dif1',
        ),
        migrations.DeleteModel(
            name='Dif2',
        ),
        migrations.DeleteModel(
            name='Same',
        ),
    ]
