# Generated by Django 5.0.7 on 2024-07-22 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_delete_dif1_delete_dif2_delete_same'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Global',
        ),
    ]
